#ifndef ENUMS_H
#define ENUMS_H

enum COLOR { RED, ORANGE, YELLOW, GREEN, BLUE, INDIGO, VIOLET };

enum TOOL {
    PENCIL, ERASER, SELECTOR,
    CIRCLE, TRIANGLE, RECTANGLE, PENTAGON, HEXAGON
};

enum ACTION {
    NONE, UNDO, REDO, CLEAR,
    BRING_FRONT, SEND_BACK,
    ENLARGE, SHRINK
};

#endif
